version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=src/main.py
      - FLASK_RUN_HOST=0.0.0.0
    command: flask run
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: celery -A src.main.celery worker --loglevel=info
  redis:
    image: "redis:alpine"
  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: pytest tests/